### ISSUE TITLE
Touch issues on demo site main navigation

### ISSUE THREAD

**Issue by Brian-CalVCB** [Office-of-Digital-Innovation/California-State-Template-v5#18]
I just looked at [http://beta.template.webtools.ca.gov](http://beta.template.webtools.ca.gov) in Chrome on my Android tablet. Tapping the top-level main navigation items opens their respective megamenus, but I can't find a way to actually activate those top level links.

Funny enough, I can use the top level links on [http://ca.gov](http://ca.gov).

**Comment by kkoryaka** [comment]
Good catch. The latest commit addresses this issue in following way. (First tap opens up the subnav items if present, the second tap goes to designated url link).

**Comment by artuoma** [comment]
Issue has been resolved.
