### ISSUE TITLE
hideSubNavs function definition is missing

### ISSUE THREAD

**Issue by jhopkinscdcr** [Office-of-Digital-Innovation/California-State-Template-v5#23]
The cagov.core.js file has four calls to the hideSubNavs function, but the function is not defined in any of the included js files.  Is it still needed?

**Comment by artuoma** [comment]
Hello sir, did you see this? if Not subscribe to all our repo alerts...



ARTEM KHOMISHEN
Web Technology Specialist
916.431.5067 (Office)
CALIFORNIA DEPARTMENT of TECHNOLOGY
________________________________

**Comment by kkoryaka** [comment]
We have removed references to that function in our latest commit.
