### ISSUE TITLE
4 calls to hideSubNavs but the function is never defined.

### ISSUE THREAD

**Issue by aklump** [Office-of-Digital-Innovation/California-State-Template-v5#24]
1. search for hideSubNavs() in cagov.core.js and you'll see it's called four times but never defined.
1. The problem shows itself in touch context.
1. This is in version 5.0 and 5.1 releases.

**Comment by kkoryaka** [comment]
We have addressed this issue  in beta-bootstrap4 version. In the next master release we will fix it too.

**Comment by aklump** [comment]
Thank you @kkoryaka, I've updated to the tip of the master branch and this fixed the error as well as a couple others that had to do with ios mobile menu.  Thank you for the quick response.
