### ISSUE TITLE
Nav items color contrast

### ISSUE THREAD

**Issue by lukefretwell** [Office-of-Digital-Innovation/California-State-Template-v5#25]
Looks like the navigational menu icon color isn't contrasting at the recommended 4.5:1 ratio. Maybe just default to the hover color?

<img width="728" alt="screen shot 2018-09-20 at 10 46 14 am" src="https://user-images.githubusercontent.com/1569463/45836725-76f14200-bcc2-11e8-95a5-e6db5bf735c4.png">

Screenshot:

<img width="1252" alt="screen shot 2018-09-20 at 10 33 52 am" src="https://user-images.githubusercontent.com/1569463/45836615-309be300-bcc2-11e8-8822-ddabe5fea450.png">

**Comment by artuoma** [comment]
Thanks for the suggestion. We actually did this intentionally not to take away from the text of the navigational menu. The icons aren't considered critical and fall in to the category of a decorative imagery.

See more information on the [Decorative Images](https://www.w3.org/WAI/tutorials/images/decorative/)

**Comment by lukefretwell** [comment]
@artuoma 👍 thank you for the quick reply!
