### ISSUE TITLE
Utilize the template with SPO

### ISSUE THREAD

**Issue by coxwagner** [Office-of-Digital-Innovation/California-State-Template-v5#26]
Can we deploy this template to our department's SharePoint Online intranet? If so, how can that be done? Thanks!

**Comment by artuoma** [comment]
As far as we know, we haven’t looked at SharePoint integration nor received feedback from anyone else. 

Based on Microsoft’s documentation you may be better off customizing one of their existing themes to mimic the state template elements and template. To fully integrate with SharePoint you will need to break the template up into parts and integrate based on how SharePoint sites are built.

The following links include Share Point documentation that you may find useful:

- https://support.office.com/en-us/article/create-and-use-site-templates-60371b0f-00e0-4c49-a844-34759ebdd989

- https://techcommunity.microsoft.com/t5/Microsoft-SharePoint-Blog/Create-and-use-custom-SharePoint-site-designs-in-Office-365/ba-p/143243 

- https://docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-theming/sharepoint-site-theming-overview 

The below link is the general template structure that you would have to consider:
- https://webstandards.ca.gov/template-structure/ 

Hope that helps!

**Comment by coxwagner** [comment]
Thanks for the info and resources @artuoma ! I'll review everything and see how we can implement this template into our department's SPO environment with best practices. The requirement is to make the home page of our intranet look just like the template you guys created. Please let me know if you guys plan to make a version of this template a SharePoint solution that we can deploy to SPO. Thanks! I appreciated.

**Comment by artuoma** [comment]
No problem, wish we could be of more help.. Let us know how you integrated it if you don't mind.
