### ISSUE TITLE
Color palette documentation

### ISSUE THREAD

**Issue by xjensen** [Office-of-Digital-Innovation/California-State-Template-v5#33]
While this template looks like a great fit for the majority CA web projects, some will not be able to use it due to technical and/or product constraints. I'm in this situation in a couple projects. (And this is of course good and fine, there will always be outliers.)

With that said, I was delighted to find the effort put into color palettes in /source/scss/colorscheme. This color work is super useful beyond the template itself, and could be applied to a wider variety of web, mobile, and other CA digital projects. I only found it because I was snooping around in your code.

I wanted to check in to see if these color palettes are documented anywhere, and if not, if there's a good place to document them within the context of this project. I'm happy to pick this up and make a contribution if desired.

Example:
https://designsystem.digital.gov/components/colors/#palette

**Comment by kkoryaka** [comment]
Thank you for your suggestions and examples. Our color scheme pages with some details can be found in the template's examples page (look for Color Schemes): http://template.webtools.ca.gov/sample/ 
Are you looking for specific color scheme that would fit your project or do you want our color schemes pages to be more documented?

**Comment by artuoma** [comment]
"more comprehensive and extensible design system" We totally agree and this is part of our road-map, thanks for your feedback!
