### ISSUE TITLE
Template use and contrast issue

### ISSUE THREAD

**Issue by Student-of-the-Web** [Office-of-Digital-Innovation/California-State-Template-v5#49]
We really need a path for updates to the template. Not a replacement, requiring rebuilding all of our content.  If anyone has the simple update process, or some steps, please let me know.
Shawn.Flanagan@waterboards.ca.gov

Also we have a contrast ADA issue in the template.
I am using "Colour Contrast Analyser" and the foreground shows #9FC7DA, and the background shows #FFFFFF, these levels of contrast fail all levels of WCAG 2.1, which is the level we at the State are required to meet.  First question is, why do we use levels we know are not ADA compliant?  Second question is, if we want all people to be able to equally perceive our content, then give out examples and templates that we know are not meeting required levels, are we not leading State staff down the wrong path; and wasting large amounts of money and time making each department figure out the issue, while dealing with lawsuit's and giving out bad code?

**Comment by kkoryaka** [comment]
Hello, we have released State Template version 5.0.6 and beta v5.5.3 that have been specifically tested for ADA compliance. Here are the demo sites http://template.webstandards.ca.gov/, http://beta.template.webstandards.ca.gov/ using those State template versions. The easiest strategy for updating your website to the latest State Template version is using our CDN (http://template.webstandards.ca.gov/cdn.html).

**Comment by Student-of-the-Web** [comment]
kkoryaka
I think the CDN idea is good, if there is a test CDN we can be linked to, that goes live a short time before the real CDN gets updated, so we could fix any issues we see in the new template.  For example, our version of 5.0.2 uses the carousel, and in version 5.0.6 the carousel only shows images if you add the class owl-carousel.  It is changes like this and others I have not yet found that make it impossible to use the CDN without a test pre-release CDN for my pages.
If you have a better idea please let me know.
  Thanks,
  Shawn.Flanagan@waterboards.ca.gov

**Comment by artuoma** [comment]
Each release will has its own CDN link so you can always keep the version you are on and reference the new CDN version link in your TEST. Does that make sense?
