### ISSUE TITLE
Alert Banner auto-closing issue

### ISSUE THREAD

**Issue by mike-adams-edd** [Office-of-Digital-Innovation/California-State-Template-v5#90]
Hello,

I have come across an issue where the alert banner at the top of the page will not allow you to click the right-hand links of the utility header when it auto-closes as you scroll down. If you click the close button before scrolling, it works just fine. If it auto-closes though, it seems the button link of the banner has a different z-index and overlays the buttons of the utility header. to test, go to http://template.webstandards.ca.gov/sample/alert-banner.html and scroll down some. Then click on the settings or contact us buttons and it will redirect you to the alert-banner page, as it is what the alert banner button is set to. Then close the alert banner instead, and the buttons should take you where you want to go.

Thanks in advance,

Mike Adams

**Comment by kkoryaka** [comment]
Thank you for your inquiry. This is a good catch. We will incorporate the fix in our next release.

**Comment by kkoryaka** [comment]
This issue should be fixed in our v5.013 and v5.5.10 beta releases.
